services:
  postgres:
    container_name: postgres-sql-qt
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - quick_talk
    restart: unless-stopped
  keycloak:
    container_name: keycloak-qt
    image: quay.io/keycloak/keycloak
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      - quick_talk
    command:
      - "start-dev"

networks:
  quick_talk:
    driver: bridge

volumes:
  postgres:
    driver: local